steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/vertex-model-training/vms-cloud'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/vertex-model-training/vms-cloud'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'vms-cloud'
      - '--image'
      - 'gcr.io/vertex-model-training/vms-cloud'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--quiet'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY