# Generated by Django 6.0 on 2026-04-14 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gateway",
            fields=[
                ("gateway_id", models.AutoField(primary_key=True, serialize=False)),
                ("gateway_name", models.CharField(max_length=150)),
                (
                    "gateway_static_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gateway_password", models.CharField(max_length=255)),
                (
                    "gateway_ssid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_mac_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_imei",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_static_wifi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_wifi_ssid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_wifi_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "gateway_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "db_table": "gateway",
            },
        ),
        migrations.CreateModel(
            name="GatewayType",
            fields=[
                ("gatewaytype_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "gatewaytype",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=150)),
                ("project_address", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("userpass", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("icon", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                ("usertype_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "usertype",
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                ("cam_id", models.AutoField(primary_key=True, serialize=False)),
                ("cam_name", models.CharField(max_length=150)),
                ("cam_url", models.URLField(blank=True, null=True)),
                ("cam_rf_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="vms.gateway",
                    ),
                ),
            ],
            options={
                "db_table": "camera",
            },
        ),
        migrations.AddField(
            model_name="gateway",
            name="gatewaytype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gateways",
                to="vms.gatewaytype",
            ),
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                ("metadata_id", models.AutoField(primary_key=True, serialize=False)),
                ("json_data", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("alert", models.BooleanField(default=False)),
                ("warning", models.BooleanField(default=False)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="vms.gateway",
                    ),
                ),
            ],
            options={
                "db_table": "metadata",
            },
        ),
        migrations.AddField(
            model_name="gateway",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gateways",
                to="vms.project",
            ),
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("sensor_id", models.AutoField(primary_key=True, serialize=False)),
                ("sensor_name", models.CharField(max_length=150)),
                (
                    "sensor_rf_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="vms.gateway",
                    ),
                ),
            ],
            options={
                "db_table": "sensor",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="vms.user",
            ),
        ),
        migrations.CreateModel(
            name="GatewayRelational",
            fields=[
                (
                    "gatewayrelational_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_relations",
                        to="vms.gateway",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_relations",
                        to="vms.user",
                    ),
                ),
            ],
            options={
                "db_table": "gatewayrelational",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="usertype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="vms.usertype",
            ),
        ),
    ]
