# Generated by Django 6.0 on 2026-07-13 06:22

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                ("cam_id", models.AutoField(primary_key=True, serialize=False)),
                ("cam_name", models.CharField(max_length=150)),
                ("cam_url", models.URLField(blank=True, null=True)),
                ("cam_rf_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "camera",
            },
        ),
        migrations.CreateModel(
            name="Gateway",
            fields=[
                ("gateway_id", models.AutoField(primary_key=True, serialize=False)),
                ("gateway_name", models.CharField(max_length=150)),
                (
                    "gateway_static_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gateway_password", models.CharField(max_length=255)),
                (
                    "gateway_ssid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_mac_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_imei",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_static_wifi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_wifi_ssid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_wifi_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "gateway_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "arm_status",
                    models.CharField(
                        choices=[("arm", "Arm"), ("disarm", "Disarm")],
                        default="disarm",
                        max_length=10,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "gateway",
            },
        ),
        migrations.CreateModel(
            name="GatewayActiveStatus",
            fields=[
                (
                    "active_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "gateway_active_status",
            },
        ),
        migrations.CreateModel(
            name="GatewayDeployStatus",
            fields=[
                (
                    "deploy_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "gateway_deploy_status",
            },
        ),
        migrations.CreateModel(
            name="GatewayStatusType",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "gateway_status_type",
            },
        ),
        migrations.CreateModel(
            name="GatewaySubType",
            fields=[
                (
                    "gatewaysubtype_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "gatewaysubtype",
            },
        ),
        migrations.CreateModel(
            name="GatewayType",
            fields=[
                ("gatewaytype_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "gatewaytype",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=150)),
                ("project_address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deployed_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="inactive",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="SensorType",
            fields=[
                ("sensortype_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sensortype",
            },
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                ("usertype_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "usertype",
            },
        ),
        migrations.CreateModel(
            name="CameraROI",
            fields=[
                ("roi_id", models.AutoField(primary_key=True, serialize=False)),
                ("roi_name", models.CharField(max_length=150)),
                ("roi_coordinates", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rois",
                        to="vms.camera",
                    ),
                ),
            ],
            options={
                "db_table": "camera_roi",
            },
        ),
        migrations.AddField(
            model_name="camera",
            name="gateway",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cameras",
                to="vms.gateway",
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="active_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gateways",
                to="vms.gatewayactivestatus",
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="deploy_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gateways",
                to="vms.gatewaydeploystatus",
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="gatewaysubtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gateways",
                to="vms.gatewaysubtype",
            ),
        ),
        migrations.AddField(
            model_name="gatewaysubtype",
            name="gatewaytype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtypes",
                to="vms.gatewaytype",
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="gatewaytype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gateways",
                to="vms.gatewaytype",
            ),
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                ("metadata_id", models.AutoField(primary_key=True, serialize=False)),
                ("json_data", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("posted_timestamp", models.DateTimeField(blank=True, null=True)),
                ("source_user_id", models.IntegerField(blank=True, null=True)),
                (
                    "device_battery",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("alert", models.BooleanField(default=False)),
                ("warning", models.BooleanField(default=False)),
                ("sensors_alert", models.BooleanField(default=False)),
                ("cam_alert", models.BooleanField(default=False)),
                ("sensors_alert_count", models.IntegerField(default=0)),
                ("cam_alert_count", models.IntegerField(default=0)),
                ("arm", models.BooleanField(default=False)),
                ("location", models.JSONField(blank=True, null=True)),
                ("phones", models.JSONField(blank=True, null=True)),
                ("sensors_alert_events", models.JSONField(blank=True, null=True)),
                ("cam_alert_events", models.JSONField(blank=True, null=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="vms.gateway",
                    ),
                ),
            ],
            options={
                "db_table": "metadata",
            },
        ),
        migrations.AddField(
            model_name="gateway",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gateways",
                to="vms.project",
            ),
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("sensor_id", models.AutoField(primary_key=True, serialize=False)),
                ("sensor_name", models.CharField(max_length=150)),
                (
                    "sensor_rf_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("value", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="vms.gateway",
                    ),
                ),
                (
                    "sensortype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensors",
                        to="vms.sensortype",
                    ),
                ),
            ],
            options={
                "db_table": "sensor",
            },
        ),
        migrations.CreateModel(
            name="SensorHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.JSONField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="vms.sensor",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_history",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("userpass", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("client_code", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "firebase_uid",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="vms.user",
                    ),
                ),
                (
                    "usertype",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vms.usertype",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_projects",
                to="vms.user",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="vms.user",
            ),
        ),
        migrations.CreateModel(
            name="GatewayStatus",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "deployment_status",
                    models.CharField(
                        choices=[
                            ("deploy_to_warehouse", "Deploy to Warehouse"),
                            ("assign_to_client", "Assign to Client"),
                            ("assign_to_customer", "Assign to Customer"),
                            ("added_to_warehouse", "Added to Warehouse"),
                            ("allotted_to_client", "Allotted to Client"),
                            ("allotted_to_customer", "Allotted to Customer"),
                            ("deployed_to_customer", "Deployed to Customer"),
                            ("active_to_customer", "Active to Customer"),
                        ],
                        default="deploy_to_warehouse",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="vms.gateway",
                    ),
                ),
                (
                    "allotted_to_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_status_records",
                        to="vms.user",
                    ),
                ),
                (
                    "allotted_to_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_status_records",
                        to="vms.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_updated_by",
                        to="vms.user",
                    ),
                ),
            ],
            options={
                "db_table": "gateway_status",
            },
        ),
        migrations.CreateModel(
            name="GatewayRelational",
            fields=[
                (
                    "gatewayrelational_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[("client", "Client"), ("customer", "Customer")],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("active_status", models.BooleanField(default=True)),
                ("last_hit_timestamp", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_relations",
                        to="vms.gateway",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gateway_relations",
                        to="vms.gatewaystatustype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_relations",
                        to="vms.user",
                    ),
                ),
            ],
            options={
                "db_table": "gatewayrelational",
            },
        ),
        migrations.AlterUniqueTogether(
            name="gatewaysubtype",
            unique_together={("gatewaytype", "name")},
        ),
    ]
