# Generated by Django 6.0 on 2026-04-24 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="allotted_to_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allotted_gateways_as_client",
                to="vms.user",
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="allotted_to_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allotted_gateways_as_customer",
                to="vms.user",
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("added_to_warehouse", "Added to Warehouse"),
                    ("allotted_to_client", "Allotted to Client"),
                    ("allotted_to_customer", "Allotted to Customer"),
                    ("deployed_to_customer", "Deployed to Customer"),
                    ("active_to_customer", "Active to Customer"),
                ],
                default="added_to_warehouse",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_projects",
                to="vms.user",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="deployed_status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="vms.user",
            ),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="gateway_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="gateway_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="usertype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vms.usertype",
            ),
        ),
    ]
