# Generated by Django 6.0 on 2026-04-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0002_gateway_allotted_to_client_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gateway",
            name="allotted_to_client",
        ),
        migrations.RemoveField(
            model_name="gateway",
            name="allotted_to_customer",
        ),
    ]
