# Generated by Django 6.0 on 2026-04-27 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0003_remove_gateway_allotted_to_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="allotted_to_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allotted_gateways_as_client",
                to="vms.user",
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="allotted_to_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allotted_gateways_as_customer",
                to="vms.user",
            ),
        ),
    ]
