# Generated by Django 6.0 on 2026-05-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0005_remove_gateway_allotted_to_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="device_status",
            field=models.CharField(default="disconnected", max_length=20),
        ),
        migrations.AddField(
            model_name="gateway",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
