# Generated by Django 6.0 on 2026-05-05 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0006_gateway_device_status_gateway_last_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayStatusType",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "gateway_status_type",
            },
        ),
        migrations.RemoveField(
            model_name="gateway",
            name="device_status",
        ),
        migrations.AddField(
            model_name="gatewayrelational",
            name="datetime",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="gatewayrelational",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gateway_relations",
                to="vms.gatewaystatustype",
            ),
        ),
    ]
