# Generated by Django 6.0 on 2026-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0007_gatewaystatustype_remove_gateway_device_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatewayrelational",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
