# Generated by Django 6.0 on 2026-05-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0008_alter_gatewayrelational_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="userpass",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="client_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
