# Generated by Django 6.0 on 2026-05-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0009_remove_user_userpass_user_address_user_client_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=255),
        ),
    ]
