# Generated by Django 6.0 on 2026-05-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0010_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="client_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="userpass",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
