# Generated by Django 6.0 on 2026-05-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0012_user_address_user_client_code_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraType",
            fields=[
                ("cameratype_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "cameratype",
            },
        ),
        migrations.CreateModel(
            name="SensorType",
            fields=[
                ("sensortype_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sensortype",
            },
        ),
        migrations.AddField(
            model_name="metadata",
            name="arm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="metadata",
            name="metadata_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="cameratype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cameras",
                to="vms.cameratype",
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="sensortype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensors",
                to="vms.sensortype",
            ),
        ),
    ]
