# Generated by Django 6.0 on 2026-05-07 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0013_cameratype_sensortype_metadata_arm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="cameratype",
        ),
        migrations.RemoveField(
            model_name="metadata",
            name="metadata_json",
        ),
        migrations.CreateModel(
            name="CameraROI",
            fields=[
                ("roi_id", models.AutoField(primary_key=True, serialize=False)),
                ("roi_name", models.CharField(max_length=150)),
                ("roi_coordinates", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rois",
                        to="vms.camera",
                    ),
                ),
            ],
            options={
                "db_table": "camera_roi",
            },
        ),
    ]
