# Generated by Django 6.0 on 2026-05-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0014_remove_camera_cameratype_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CameraType",
        ),
    ]
