# Generated by Django 6.0 on 2026-05-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0016_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="arm_status",
            field=models.CharField(
                choices=[("arm", "Arm"), ("disarm", "Disarm")],
                default="disarm",
                max_length=10,
            ),
        ),
    ]
