# Generated by Django 6.0 on 2026-05-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0017_gateway_arm_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayActiveStatus",
            fields=[
                (
                    "active_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (
                                "all_data_found_device_connected",
                                "All Data Found Device Connected",
                            ),
                            (
                                "no_data_found_device_connected",
                                "No Data Found Device Connected",
                            ),
                            (
                                "no_data_no_device_connected",
                                "No Data No Device Connected",
                            ),
                            (
                                "device_connected_wrong_data",
                                "Device Connected Wrong Data",
                            ),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "gateway_active_status",
            },
        ),
        migrations.CreateModel(
            name="GatewayDeploymentStatus",
            fields=[
                (
                    "deployment_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("added_to_warehouse", "Added to Warehouse"),
                            ("allotted_to_client", "Allotted to Client"),
                            ("allotted_to_customer", "Allotted to Customer"),
                            ("deployed_to_customer", "Deployed to Customer"),
                            ("active_to_customer", "Active to Customer"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "gateway_deployment_status",
            },
        ),
        migrations.RemoveField(
            model_name="gatewayrelational",
            name="status",
        ),
        migrations.AddField(
            model_name="gateway",
            name="active_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gatewaysactive",
                to="vms.gatewayactivestatus",
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="deployment_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gatewaysdeployment",
                to="vms.gatewaydeploymentstatus",
            ),
        ),
        migrations.DeleteModel(
            name="GatewayStatus",
        ),
        migrations.DeleteModel(
            name="GatewayStatusType",
        ),
    ]
