# Generated by Django 6.0 on 2026-05-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0018_gatewayactivestatus_gatewaydeploymentstatus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gatewayactivestatus",
            name="description",
        ),
        migrations.RemoveField(
            model_name="gatewaydeploymentstatus",
            name="description",
        ),
    ]
