# Generated by Django 6.0 on 2026-05-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0019_remove_gatewayactivestatus_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayStatusType",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "gateway_status_type",
            },
        ),
        migrations.RemoveField(
            model_name="gateway",
            name="active_status",
        ),
        migrations.RemoveField(
            model_name="gateway",
            name="deployment_status",
        ),
        migrations.CreateModel(
            name="GatewayStatus",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "deployment_status",
                    models.CharField(
                        choices=[
                            ("added_to_warehouse", "Added to Warehouse"),
                            ("allotted_to_client", "Allotted to Client"),
                            ("allotted_to_customer", "Allotted to Customer"),
                            ("deployed_to_customer", "Deployed to Customer"),
                            ("active_to_customer", "Active to Customer"),
                        ],
                        default="added_to_warehouse",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allotted_to_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_status_records",
                        to="vms.user",
                    ),
                ),
                (
                    "allotted_to_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_status_records",
                        to="vms.user",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="vms.gateway",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_updated_by",
                        to="vms.user",
                    ),
                ),
            ],
            options={
                "db_table": "gateway_status",
            },
        ),
        migrations.AddField(
            model_name="gatewayrelational",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gateway_relations",
                to="vms.gatewaystatustype",
            ),
        ),
        migrations.DeleteModel(
            name="GatewayActiveStatus",
        ),
        migrations.DeleteModel(
            name="GatewayDeploymentStatus",
        ),
    ]
