# Generated by Django 6.0 on 2026-06-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0024_gatewayrelational_relation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
