# Generated by Django 6.0 on 2026-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0025_sensor_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="sensor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
