# Generated by Django 6.0 on 2026-06-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0026_sensor_created_at_sensor_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.JSONField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="vms.sensor",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_history",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
