# Generated by Django 6.0 on 2026-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0027_sensorhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="icon",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
