# Generated by Django 6.0 on 2026-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0028_remove_user_icon_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
        migrations.AddField(
            model_name="user",
            name="icon",
            field=models.URLField(blank=True, null=True),
        ),
    ]
