# Generated by Django 6.0 on 2026-07-03 06:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0029_remove_user_image_user_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="icon",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
