# Generated by Django 6.0 on 2026-07-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0030_remove_user_icon_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
