"""
Django settings for vmscloud project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


import os
from pathlib import Path
import cloudinary


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from pathlib import Path
import firebase_admin
from firebase_admin import credentials

import json

if not firebase_admin._apps:
    firebase_json = os.environ.get('FIREBASE_CREDENTIALS_JSON')
    if firebase_json:
        # Running on Cloud Run - credentials come from env var
        cred = credentials.Certificate(json.loads(firebase_json))
    else:
        # Running locally - fall back to the local file
        local_path = os.path.join(BASE_DIR, 'firebase-credentials.json')
        if os.path.exists(local_path):
            cred = credentials.Certificate(local_path)
        else:
            raise Exception("No Firebase credentials found (neither FIREBASE_CREDENTIALS_JSON env var nor local firebase-credentials.json file)")
    firebase_admin.initialize_app(cred)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_9*+lyv(2hm9dwcn=+m3#h3aa(!&x*+f%)fas9@^17f2zd*!ix"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['vms-cloud-382170497486.us-central1.run.app',
                "127.0.0.1",
                "localhost",
                "192.168.18.24"
                 ]
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
     "cloudinary_storage",
    "django.contrib.staticfiles",
    "cloudinary",
    'vms',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
     
   
]
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": "dvjuffilc",
    "API_KEY": "532877263839368",
    "API_SECRET": "NT29SAFd48kR5ddrC80HYl3ZTu8",
}
cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE["CLOUD_NAME"],
    api_key=CLOUDINARY_STORAGE["API_KEY"],
    api_secret=CLOUDINARY_STORAGE["API_SECRET"],
    secure=True,
)

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# AUTH_USER_MODEL = "vms.User"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
         'vms.authentication.FirebaseAuthentication',
    ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vmscloud.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vmscloud.wsgi.application"


# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# # Get environment variables (these should be set in Cloud Run)

DB_USER = "mexemaic_user"
DB_PASS = "w_bazcGNxR9VW(&z"
DB_NAME = "mexemaic_db"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASS,
        "HOST": "74.50.90.187",
        "PORT": "3306",
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "connect_timeout": 60,
        },
        "CONN_MAX_AGE": 60,
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://hatwebserver-382170497486.us-central1.run.app",
]
CSRF_TRUSTED_ORIGINS = [
    "https://hatwebserver-382170497486.us-central1.run.app",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://192.168.18.11:8000",
    "http://192.168.18.24:8000",
]
CORS_ALLOW_ALL_ORIGINS = True



