# Generated by Django 4.2.19 on 2025-10-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway_id", models.CharField(max_length=100, unique=True)),
                ("gateway_mac", models.CharField(max_length=100, unique=True)),
                ("alert_status", models.CharField(default="0", max_length=10)),
                ("warning_status", models.CharField(default="0", max_length=10)),
                ("arm", models.CharField(default="0", max_length=10)),
                ("address", models.TextField()),
                ("latitude", models.CharField(max_length=50)),
                ("longitude", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_type", models.CharField(max_length=50)),
                ("sid", models.CharField(max_length=50)),
                ("mid", models.CharField(max_length=100)),
                ("uname", models.CharField(max_length=100)),
                ("status", models.CharField(default="0", max_length=10)),
                ("battery", models.CharField(blank=True, max_length=20, null=True)),
                ("rf", models.CharField(default="ok", max_length=20)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="ems_app.gateway",
                    ),
                ),
            ],
        ),
    ]
