# Generated by Django 4.2.19 on 2025-10-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ems_app", "0002_sensorgateway_sensor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensor",
            old_name="mid",
            new_name="mac_id",
        ),
        migrations.RenameField(
            model_name="sensor",
            old_name="sid",
            new_name="sensor_id",
        ),
        migrations.RenameField(
            model_name="sensor",
            old_name="uname",
            new_name="sensor_name",
        ),
        migrations.RemoveField(
            model_name="sensor",
            name="rf",
        ),
        migrations.RemoveField(
            model_name="sensorgateway",
            name="created_at",
        ),
        migrations.AddField(
            model_name="sensor",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sensor",
            name="rf_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="battery",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="gateway",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensors",
                to="ems_app.sensorgateway",
            ),
        ),
        migrations.AlterField(
            model_name="sensorgateway",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensorgateway",
            name="gateway_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="sensorgateway",
            name="gateway_mac",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sensorgateway",
            name="latitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="sensorgateway",
            name="longitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
