# Generated by Django 4.2.21 on 2025-11-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ems_app",
            "0003_rename_mid_sensor_mac_id_rename_sid_sensor_sensor_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
