# Generated by Django 5.2.5 on 2025-10-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ems_app",
            "0003_rename_mid_sensor_mac_id_rename_sid_sensor_sensor_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
