# Generated by Django 4.2.21 on 2025-11-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0004_user_reset_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="is_on",
            field=models.BooleanField(default=False),
        ),
    ]
