# Generated by Django 4.2.21 on 2025-11-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0005_sensor_is_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gateways",
            name="analyzers",
        ),
        migrations.RemoveField(
            model_name="gateways",
            name="analyzers_by_port",
        ),
        migrations.RemoveField(
            model_name="gateways",
            name="project",
        ),
        migrations.RemoveField(
            model_name="gateways",
            name="user_id",
        ),
    ]
