# Generated by Django 4.2.21 on 2025-11-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0006_remove_gateways_analyzers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateways",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ems_app.user",
            ),
        ),
    ]
