# Generated by Django 4.2.21 on 2025-11-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0007_gateways_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateways",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gateways",
            name="latitude",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="gateways",
            name="longitude",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
