# Generated by Django 4.2.21 on 2025-11-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0008_gateways_address_gateways_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateways",
            name="alert_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="gateways",
            name="arm",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="gateways",
            name="warning_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
