# Generated by Django 4.2.21 on 2025-11-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0010_alter_sensor_gateway"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="gateway",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensors",
                to="ems_app.gateways",
            ),
        ),
    ]
