# Generated by Django 4.2.21 on 2025-11-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0011_alter_sensor_gateway"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gateways",
            name="alert_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gateways",
            name="warning_status",
            field=models.BooleanField(default=False),
        ),
    ]
