# Generated by Django 4.2.21 on 2025-11-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0012_alter_gateways_alert_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gateways",
            name="arm",
            field=models.BooleanField(default=False),
        ),
    ]
