# Generated by Django 4.2.21 on 2025-11-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0013_alter_gateways_arm"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateways",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
