# Generated by Django 4.2.21 on 2025-11-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems_app", "0014_gateways_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateways",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
